openapi: 3.0.0
info:
  title: testing assignment API
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:3000
  variables: {}
paths:
  /country:
    get:
      tags:
      - Misc
      summary: localhost:3000/country?id=7fc020e1&startYear=2006&endYear=2012&params=CO2,HFC,GHG
      operationId: localhost:3000/country?id=7fc020e1&startYear=2006&endYear=2012&params=CO2,HFC,GHG
      parameters:
      - name: id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 7fc020e1
      - name: startYear
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 2003
      - name: endYear
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 2010
      - name: params
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: CO2,HFC,GHG
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /countries:
    get:
      tags:
      - Misc
      summary: localhost:3000/countries
      operationId: localhost:3000/countries
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /listcountries:
    get:
      tags:
      - Misc
      summary: localhost:3000/listcountries
      operationId: localhost:3000/listcountries
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /listcategories:
    get:
      tags:
      - Misc
      summary: localhost:3000/listcategories
      operationId: localhost:3000/listcategories
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /:
    get:
      tags:
      - Misc
      summary: localhost:3000/
      operationId: localhost:3000/
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
tags:
- name: Misc
  description: ''
