name: Changelog-demo
on: [push]
jobs:
  Log-Start-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Let's test changelog generation"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 100

      - name: Build Changelog
        if: startsWith(github.ref, 'refs/tags/test')
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: release-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.TEMP_ACTION }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          token: ${{ secrets.TEMP_ACTION }}
          body: ${{steps.github_release.outputs.changelog}}
